export const INIT_CRYPTOS = 'INIT_CRYPTOS';
export const INIT_CURRENT_CURRENCY = 'INIT_CURRENT_CURRENCY';
export const INIT_CURRENCY_CLICK_TO_ENTER = 'INIT_CURRENCY_CLICK_TO_ENTER';
export const INIT_SECOND_CURRENCY = 'INIT_SECOND_CURRENCY';
export const INIT_SECOND_CURRENCY_CLICK_TO_ENTER = 'INIT_SECOND_CURRENCY_CLICK_TO_ENTER';
export const INIT_SEND_NUMBER_VALUE = 'INIT_SEND_NUMBER_VALUE';
export const INIT_CRYPTOS_PRICE = 'INIT_CRYPTOS_PRICE';
export const INIT_CONVERT_VALUE = ' INIT_CONVERT_VALUE';